// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getBookInfo: (bookId: string) => __TAURI_INVOKE<[BookInfo, VolumeInfo[]]>("get_book_info", { bookId }),
	download: (bookId: string, bookInfo: BookInfo, volumeList: VolumeInfo[], volumeNoList: number[]) => __TAURI_INVOKE<null>("download", { bookId, bookInfo, volumeList, volumeNoList }),
	cancelDownload: () => __TAURI_INVOKE<null>("cancel_download"),
	browserUrl: (url: string) => __TAURI_INVOKE<string>("browser_url", { url }),
	saveConfig: (newConfig: Config) => __TAURI_INVOKE<null>("save_config", { newConfig }),
	getConfigVue: () => __TAURI_INVOKE<Config>("get_config_vue"),
	checkUpdate: () => __TAURI_INVOKE<string>("check_update"),
	getVersion: () => __TAURI_INVOKE<string>("get_version"),
	getBooks: () => __TAURI_INVOKE<Book[]>("get_books"),
	createIndex: () => __TAURI_INVOKE<null>("create_index"),
};

/* Types */
export type Book = {
	id: string,
	title: string | null,
	author: string | null,
	publisher: string | null,
	tags: string[],
	description: string | null,
	volume_list: Volume[],
};

export type BookInfo = {
	title: string | null,
	author: string | null,
	publisher: string | null,
	tags: string[],
	description: string | null,
	cover: string | null,
};

export type CommandError = string;

export type Config = {
	output?: string,
	template?: string,
	cookie?: string,
	userAgent?: string,
	headers?: { [key in string]: string },
	sleepTime?: number,
	baseUrl?: string,
	addCatalog?: boolean,
	errorImg?: string[],
	autoCheckUpdate?: boolean,
	convertSimpleChinese?: boolean,
	debug?: boolean,
};

export type Volume = {
	id: string,
	title: string | null,
	url_vol: string,
	volume_no: number,
	updated_at: string,
	path: string,
};

export type VolumeInfo = {
	title: string | null,
	chapter_list: string[],
	chapter_path_list: string[],
	url_vol: string | null,
	volume_no: number,
	cover: string | null,
};

