/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoCheckUpdate: typeof import('./components/AutoCheckUpdate.vue')['default']
    Config: typeof import('./views/Config.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Search: typeof import('./views/Search.vue')['default']
    Web: typeof import('./views/Web.vue')['default']
  }
}
